-- MySQL Script generated by MySQL Workbench
-- 05/06/15 13:11:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
drop database if exists dbEngenhariaServico;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbEngenhariaServico` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbEngenhariaServico` ;

-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `perfil` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(240) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `codProduto` VARCHAR(25) NOT NULL,
  `produto` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`Remetente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`Remetente` (
  `idRemetente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(2) NULL,
  `email` VARCHAR(45) NULL,  
  `telefone` VARCHAR(15) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRemetente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`Tecnico` (
  `idTecnico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTecnico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`ManutencaoLaboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`ManutencaoLaboratorio` (
  `idManutencaoLaboratorio` INT NOT NULL AUTO_INCREMENT,
  `numSerie` VARCHAR(5) NULL,
  `produto` VARCHAR(45) NOT NULL,
  `remetente` VARCHAR(15) NOT NULL,
  `defeitoRelatado` VARCHAR(15) NULL,
  `parecerTecnico` VARCHAR(15) NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `camadoOat` VARCHAR(5) NULL,
  `descricaoAtividades` VARCHAR(45) NOT NULL,
  `materialUtilizado` VARCHAR(45) NULL,
  `tempoReparo` VARCHAR(10) NOT NULL,
  `Remetente_idRemetente` INT NOT NULL,
  `Tecnico_idTecnico` INT NOT NULL,
  PRIMARY KEY (`idManutencaoLaboratorio`),
  INDEX `fk_ManutencaoLaboratorio_Remetente1_idx` (`Remetente_idRemetente` ASC),
  INDEX `fk_ManutencaoLaboratorio_Tecnico1_idx` (`Tecnico_idTecnico` ASC),
  CONSTRAINT `fk_ManutencaoLaboratorio_Remetente1`
    FOREIGN KEY (`Remetente_idRemetente`)
    REFERENCES `mydb`.`Remetente` (`idRemetente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ManutencaoLaboratorio_Tecnico1`
    FOREIGN KEY (`Tecnico_idTecnico`)
    REFERENCES `mydb`.`Tecnico` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`Componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`Componente` (
  `idComponente` INT NOT NULL AUTO_INCREMENT,
  `codComponente` VARCHAR(25) NOT NULL,
  `componente` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComponente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEngenhariaServico`.`Produto_has_ManutencaoLaboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEngenhariaServico`.`Produto_has_ManutencaoLaboratorio` (
  `Produto_idProduto` INT NOT NULL,
  `ManutencaoLaboratorio_idManutencaoLaboratorio` INT NOT NULL,
  `Componente_idComponente` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `ManutencaoLaboratorio_idManutencaoLaboratorio`, `Componente_idComponente`),
  INDEX `fk_Produto_has_ManutencaoLaboratorio_ManutencaoLaboratorio1_idx` (`ManutencaoLaboratorio_idManutencaoLaboratorio` ASC),
  INDEX `fk_Produto_has_ManutencaoLaboratorio_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Produto_has_ManutencaoLaboratorio_Componente1_idx` (`Componente_idComponente` ASC),
  CONSTRAINT `fk_Produto_has_ManutencaoLaboratorio_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_ManutencaoLaboratorio_ManutencaoLaboratorio1`
    FOREIGN KEY (`ManutencaoLaboratorio_idManutencaoLaboratorio`)
    REFERENCES `mydb`.`ManutencaoLaboratorio` (`idManutencaoLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_ManutencaoLaboratorio_Componente1`
    FOREIGN KEY (`Componente_idComponente`)
    REFERENCES `mydb`.`Componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

